services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    restart: unless-stopped

  ghost:
    image: ghost:6-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      url: ${GHOST_URL:-http://localhost:2368}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ghost
      mail__transport: SMTP
      mail__from: "Ghost <no-reply@example.com>"
      mail__options__host: mailpit
      mail__options__port: 1025
      mail__options__secure: "false"
      mail__options__auth__user: ""
      mail__options__auth__pass: ""
    ports:
      - "2368:2368"
    volumes:
      - ./data/ghost:/var/lib/ghost/content
      - ./themes:/var/lib/ghost/content/themes
    restart: unless-stopped
